[phases.setup]
nixPkgs = [
  "python312",  # Or python310 if you're using that
  "python312Packages.setuptools",
  "python312Packages.pip",
  "python312Packages.wheel",
  "python312Packages.distutils"
]
[phases.build]
commands = [
  "pip freeze"  # This will list all installed packages in the environment
]
