
[phases.setup]
nixPkgs = [
  "python312",                      # Python 3.12 interpreter
  "python312Packages.setuptools",    # Ensure setuptools is available
  "python312Packages.pip",           # Ensure pip is available
  "python312Packages.wheel",        # Ensure wheel is available
  "python312Packages.distutils"     # Critical for building many packages that need compilation
]

[phases.install]
#  Nixpacks will often automatically handle this, but you can add custom commands if needed
cmds = ["pip install -r requirements.txt"]

[start]
#  Adjust this to match your application's startup command
cmd = "python app.py"
