[phases.setup]
nixPkgs = [
  "python311",  # Or python310 if you're using that
  "python311Packages.setuptools",
  "python311Packages.pip",
  "python311Packages.wheel",
  "python311Packages.distutils"
]
[phases.build]
commands = [
  "pip freeze"  # This will list all installed packages in the environment
]
