[phases.setup]
nixPkgs = ["...", "gcc", "python312"]

[phases.install]
#  Nixpacks will often automatically handle this, but you can add custom commands if needed
cmds = ["pip install -r requirements.txt"]

[start]
#  Adjust this to match your application's startup command
cmd = "python app.py"
