[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.distutils",
  "python312Packages.setuptools",
  "python312Packages.pip",
  "python312Packages.wheel",
]
[phases.build]
commands = [
  "pip freeze"  # This will list all installed packages in the environment
]
