
[phases.setup]
nixPkgs = [
  "python312",                      # Python 3.12 interpreter
  "python312Packages.setuptools",    # Ensure setuptools is available
  "python312Packages.pip",           # Ensure pip is available
  "python312Packages.wheel",        # Ensure wheel is available
]
